# Generated by Django 4.2.16 on 2024-09-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singers',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.singer'),
        ),
    ]
